#!/usr/bin/python3
# -*- coding: utf-8 -*-
# vim: tabstop=8 expandtab shiftwidth=4 softtabstop=4

"""
Analyse the RetractionNature field (Retraction, Expression of Concern,
Correction, Reinstatement) by publisher.

Outputs:
  results/retraction-nature.tex
"""

import pandas as pd

FILTERED_CSV = 'filtered-all-types.csv'
RESULTS_TEX = 'results/retraction-nature.tex'

PUBLISHERS = {
    'ACM': ['Association for Computing Machinery (ACM)'],
    'IEEE': ['IEEE: Institute of Electrical and Electronics Engineers'],
    'Elsevier': ['Elsevier', 'Elsevier - Cell Press'],
    'Springer Nature': ['Springer', 'Springer - Nature Publishing Group', 'Springer - Biomed Central (BMC)'],
    'Wiley': ['Wiley'],
    'Taylor & Francis': ['Taylor and Francis', 'Taylor and Francis - Dove Press'],
    'SAGE': ['SAGE Publications'],
    'Hindawi': ['Hindawi'],
    'IOS Press': ['IOS Press (bought by Sage November 2023)'],
    'PLoS': ['PLoS'],
}

PUBLISHER_LABELS = {}
for k, v_list in PUBLISHERS.items():
    for v in v_list:
        PUBLISHER_LABELS[v] = k

NATURE_ORDER = ['Retraction', 'Expression of concern', 'Correction', 'Reinstatement']


def main():
    df = pd.read_csv(FILTERED_CSV, encoding='iso-8859-1')
    df['PublisherLabel'] = df['Publisher'].map(PUBLISHER_LABELS)
    df = df.dropna(subset=['PublisherLabel'])
    total = len(df)

    # ---- 1. Global breakdown ------------------------------------------------
    global_counts = df['RetractionNature'].value_counts()
    print('GLOBAL RETRACTION NATURE')
    print('=' * 60)
    for nat in NATURE_ORDER:
        n = global_counts.get(nat, 0)
        print(f'  {nat:<25s}  {n:>6,}  ({n/total*100:.1f}%)')
    print()

    # ---- 2. Per-publisher crosstab ------------------------------------------
    ct = pd.crosstab(df['PublisherLabel'], df['RetractionNature'])
    # Ensure all nature columns present
    for nat in NATURE_ORDER:
        if nat not in ct.columns:
            ct[nat] = 0
    ct = ct[NATURE_ORDER]
    ct['Total'] = ct.sum(axis=1)

    print('PER-PUBLISHER RETRACTION NATURE')
    print('=' * 90)
    header = f'{"Publisher":<22s}'
    for nat in NATURE_ORDER:
        short = nat[:6]
        header += f'  {short:>7s}  {"%":>5s}'
    print(header)
    print('-' * 90)

    pub_rows = []
    for label in PUBLISHERS.keys():
        if label not in ct.index:
            continue
        row = ct.loc[label]
        t = row['Total']
        parts = f'{label:<22s}'
        row_data = {'publisher': label, 'total': t}
        for nat in NATURE_ORDER:
            n = row[nat]
            pct = n / t * 100 if t else 0
            parts += f'  {n:>7,}  {pct:>4.1f}%'
            row_data[nat] = n
            row_data[f'{nat}_pct'] = pct
        print(parts)
        pub_rows.append(row_data)
    print()

    # ---- 3. Write results .tex ----------------------------------------------
    lines = []
    lines.append('% Retraction Nature Analysis')
    lines.append('% Generated by: 9-retraction-nature.py')
    lines.append('%')
    lines.append('% Breakdown of the RetractionNature field (Retraction, Expression')
    lines.append('% of Concern, Correction, Reinstatement) across publishers.')
    lines.append('')

    # Key findings as comments
    lines.append('% --- Key Findings ---')
    lines.append(f'% Total entries: {total:,}')
    for nat in NATURE_ORDER:
        n = global_counts.get(nat, 0)
        lines.append(f'% {nat}: {n:,} ({n/total*100:.1f}%)')
    lines.append('%')

    # ACM / IEEE highlights
    for label in ['ACM', 'IEEE']:
        row = next(r for r in pub_rows if r['publisher'] == label)
        parts = []
        for nat in NATURE_ORDER:
            n = row[nat]
            if n > 0:
                parts.append(f'{nat} {n:,} ({row[f"{nat}_pct"]:.1f}%)')
        lines.append(f'% {label}: ' + '; '.join(parts))
    lines.append('')

    # Table: Per-publisher retraction nature
    lines.append('\\begin{table*}[htbp]')
    lines.append('  \\centering')
    lines.append('  \\small')
    lines.append('  \\caption{Retraction nature by publisher. Each entry in the '
                 'Retraction Watch database is classified as a retraction, expression '
                 'of concern, correction, or reinstatement.}')
    lines.append('  \\label{tab:retraction-nature}')
    lines.append('  \\begin{tabular}{l r r r r r r r r}')
    lines.append('    \\toprule')
    lines.append('    & \\multicolumn{2}{c}{Retraction} '
                 '& \\multicolumn{2}{c}{Expression of} '
                 '& \\multicolumn{2}{c}{Correction} '
                 '& \\multicolumn{2}{c}{Reinstatement} \\\\')
    lines.append('    & \\multicolumn{2}{c}{} '
                 '& \\multicolumn{2}{c}{Concern} '
                 '& \\multicolumn{2}{c}{} '
                 '& \\multicolumn{2}{c}{} \\\\')
    lines.append('    \\cmidrule(lr){2-3} \\cmidrule(lr){4-5} '
                 '\\cmidrule(lr){6-7} \\cmidrule(lr){8-9}')
    lines.append('    Publisher & N & \\% & N & \\% & N & \\% & N & \\% \\\\')
    lines.append('    \\midrule')

    for row in pub_rows:
        pub = row['publisher'].replace('&', '\\&')
        cells = [f'{pub}']
        for nat in NATURE_ORDER:
            n = row[nat]
            pct = row[f'{nat}_pct']
            cells.append(f'{n:,}')
            cells.append(f'{pct:.1f}')
        lines.append('    ' + ' & '.join(cells) + ' \\\\')

    # Totals row
    cells = ['\\textbf{Total}']
    for nat in NATURE_ORDER:
        n = global_counts.get(nat, 0)
        cells.append(f'{n:,}')
        cells.append(f'{n/total*100:.1f}')
    lines.append('    \\midrule')
    lines.append('    ' + ' & '.join(cells) + ' \\\\')

    lines.append('    \\bottomrule')
    lines.append('  \\end{tabular}')
    lines.append('\\end{table*}')
    lines.append('')

    with open(RESULTS_TEX, 'w') as f:
        f.write('\n'.join(lines) + '\n')

    print(f'Results written to {RESULTS_TEX}')


if __name__ == '__main__':
    main()
